# Set the new prefix to Ctrl+w
set -g prefix C-w
# Free the original Ctrl+b prefix binding
unbind C-b

# Ensure that we can send Ctrl+w to other apps by pressing it twice
bind C-w send-prefix

# Scrolling for Claude and such...
set -g mouse on

# helps in faster key repetition
set -sg escape-time 0

# start session number from 1 rather than 0
set -g base-index 1

# start pane number from 1 similar to windows
set -g pane-base-index 1

# vertical split
bind \\ split-window -h

# horizontal split
bind - split-window -v
