# Set the new prefix to Ctrl+a
set -g prefix C-a
# Free the original Ctrl+b prefix binding
unbind C-b

# Ensure that we can send Ctrl+a to other apps by pressing it twice
bind C-a send-prefix

# Use screen-256color since tmux-256color terminfo entry is missing on some systems
set -g default-terminal "screen-256color"

# pane movement similar to vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Scrolling for Claude and such...
set -g mouse on

# helps in faster key repetition
set -sg escape-time 0

# start session number from 1 rather than 0
set -g base-index 1

# start pane number from 1 similar to windows
set -g pane-base-index 1

# vertical split
bind \\ split-window -h

# horizontal split
bind - split-window -v

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'gruvbox'
set -g @tmux2k-left-plugins "session cwd"
set -g @tmux2k-right-plugins "cpu ram time"
set -g @tmux2k-cwd-icon "WD:"
set -g @tmux2k-cpu-icon "CPU:"
set -g @tmux2k-ram-icon "RAM:"

# Initialize TPM (keep this line at the very bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Use vi-style
setw -g mode-keys vi

# Window moving
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1
